"""empty message

Revision ID: 72687519906f
Revises: 
Create Date: 2025-03-17 20:01:12.868613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72687519906f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=False),
    sa.Column('year', sa.String(length=80), nullable=False),
    sa.Column('cover_image', sa.String(length=250), nullable=False),
    sa.Column('genre', sa.String(length=250), nullable=False),
    sa.Column('have', sa.String(length=80), nullable=False),
    sa.Column('youtube_link', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('encoded_password', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('sur_name', sa.String(length=120), nullable=True),
    sa.Column('username', sa.String(length=120), nullable=True),
    sa.Column('mobile_number', sa.String(length=120), nullable=True),
    sa.Column('post_code', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('region_state', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('mobile_number'),
    sa.UniqueConstraint('username')
    )
    op.create_table('comentario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=250), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['album.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_album', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_album'], ['album.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.Column('precio_total', sa.Float(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('shipping_name', sa.String(length=120), nullable=True),
    sa.Column('shipping_address', sa.String(length=250), nullable=True),
    sa.Column('shipping_city', sa.String(length=120), nullable=True),
    sa.Column('shipping_cp', sa.String(length=20), nullable=True),
    sa.Column('shipping_country', sa.String(length=120), nullable=True),
    sa.Column('shipping_contactNumber', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['album.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedido')
    op.drop_table('favorito')
    op.drop_table('comentario')
    op.drop_table('user')
    op.drop_table('album')
    # ### end Alembic commands ###
